site_name: Mesor Structor
site_description: Mesor Structor Documentation
site_author: containo.us
site_url: https://containous.github.io
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/structor'

docs_dir: 'docs'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: en
  include_sidebar: true
  favicon: img/containous.icon.png
  logo: img/containous.logo.png
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2016-2018 Containous SAS"

extra_css:
  - theme/styles/extra.css
  - theme/styles/atom-one-light.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true

# Page tree
pages:
  - Getting Started: index.md
